spring.application.name=example2
spring.datasource.url=jdbc:postgresql://localhost:5432/tp_foyer2
spring.datasource.username=postgres
spring.datasource.password=admin
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true
server.servlet.context-path=/example2
server.port=8081